name: clap
description: A library to parse OpenClap files
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  uuid: ^3.0.0
  yaml: ^3.1.0
  http: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  path: ^1.8.0